# Generated by Django 4.0.4 on 2023-01-21 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.TextField(unique=True)),
                ('bookAuthor', models.TextField()),
                ('bookCover', models.TextField()),
                ('bookLink', models.TextField()),
                ('bookSize', models.IntegerField(null=True)),
                ('book', models.FileField(null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Found books',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.TextField()),
                ('level', models.IntegerField(choices=[(0, 'DEBUG'), (1, 'INFO'), (2, 'WARNING'), (3, 'ERROR')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchRequest', models.TextField(unique=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('books', models.ManyToManyField(to='api.book')),
            ],
            options={
                'verbose_name_plural': 'Search requests',
                'ordering': ['-timestamp'],
            },
        ),
    ]
