# Generated by Django 4.0.4 on 2022-08-10 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookLink', models.TextField()),
                ('bookSize', models.IntegerField()),
                ('book', models.FileField(upload_to='')),
                ('bookPath', models.FilePathField()),
            ],
            options={
                'verbose_name_plural': 'Found books',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('hashId', models.IntegerField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Search requests',
            },
        ),
        migrations.CreateModel(
            name='BooksToSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foundbook')),
                ('searchRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.searchrequest')),
            ],
        ),
    ]
